### ISSUE TITLE
[Bug] TCPv6 causes a network error

### ISSUE THREAD

**Issue by pitsi** [elgatito/plugin.video.elementum#141]
So, after upgrading to 0.0.44, elementum crashes on startup. All kodi reports via its notifications is 

```
Elementum - Could not start torrent client. Please restart
Elementum - Elementum has crashed, restarting

Elementum - Could not start torrent client. Please restart
Elementum - Elementum has crashed, restarting

Elementum - Could not start torrent client. Please restart
Elementum - Elementum has crashed, restarting

Elementum - Crashed too many times, aborting
```
And here is the entire log file, because I can't clean it up and keep only the parts that mention elementum
https://paste.debian.net/1021427/

I have tried deleting ~/.kodi/userdata/addon_data/plugin.video.elementum and setting it up again, as well as reinstalling it. There are no .fastresume files anywhere that someone suggested deleting in a similar issue.

Debian testing x64 and kodi 17.6.

**Comment by elgatito** [comment]
@pitsi you have problems with using TCP6 address. I will try to fix that in the next version.

**Comment by nickgrishaev** [comment]
I have this problem too.
My kodi log - https://www.dropbox.com/s/3w42mb3t9tomzbu/kodi.log?dl=0

**Comment by elgatito** [comment]
```
&errors.errorString{s:"subsequent listen: listen tcp6 :33515: socket: address family not supported by protocol"}
```

Yes, looks the same. You have not configured to use specific network interface in Elementum's Kodi settings?

**Comment by nickgrishaev** [comment]
Eth0 interface was enabled and use DHCP.
WiFi interface was disabled.
All configuration was done in Kodi UI. 
My router does not support IPv6

**Comment by pitsi** [comment]
I also have ipv6 disabled completely in my system with this kernel parameter 

`BOOT_IMAGE=/boot/vmlinuz-4.15.0-2-amd64 root=/dev/sda3 ro nomodeset noresume net.ifnames=0 **ipv6.disable=1** libahci.ignore_sss=1 quiet`

Wired only interface, static ip

**Comment by pitsi** [comment]
Just to let you know, removing that parameter from my kernel's boot options and thus enabling ipv6 makes elementum start normally.

**Comment by elgatito** [comment]
Fix is in place. Should be fixed with 0.0.45.

**Comment by pitsi** [comment]
I manually upgraded to 0.0.45 (= downloaded the x64 linux version and installed from zip), because it did not auto update.
And it still fails to start. Here is the new log (pastebin will probably make it available for 3 days)

http://paste.debian.net/1022420/

**Comment by elgatito** [comment]
I have made changes on my side, but that is not enough. Have to wait for torrent library changes as well.

**Comment by pitsi** [comment]
Oh well...
Ok then. I will enable ipv6 usage on my system just for elementum. Please keep us informed and this issue report open until then. Thank you :)

**Comment by elgatito** [comment]
Please, try with the 0.0.46, library was fixed to avoid listening the TCPv6 when not needed.

**Comment by pitsi** [comment]
It still fails to start and I think the reason is the same.
http://paste.debian.net/1023814/

It starts as it should with ipv6 enabled.

I have 2 extra questions though...
1) Why does elementum have to know all those xdg related stuff like my dekstop enviroment, my display manager, my shell etc?
2) What changed from 0.0.43 to 0.0.44 and newer and is causing all this? I assume it is the torrent client, because I tried to watch something in elementum a few days ago and it did not even start downloading. I would make another issue, but I would like to see this one solved first, so as to rule out ipv6 related issues.

**Comment by elgatito** [comment]
@pitsi will make another change with the next version. 

> 1. 
It does not need anything listed.
> 2. 
torrent library added tcpv6.

**Comment by nickgrishaev** [comment]
My kodi log:
https://www.dropbox.com/s/3w42mb3t9tomzbu/kodi.log?dl=0

Only 0.0.43 version is work for me.
All revision has error: subsequent listen: listen tcp6 :40353: socket: address family not supported by protocol"

**Comment by pitsi** [comment]
I just noticed version 0.0.47 was released a few hours ago, so I updated it manually as usual.
It seems to launch properly now and the log seems clean, so I can say it is finally solved. Any feedback from others will be valuable though.

**Comment by elgatito** [comment]
That is great to hear. Sorry for such a late update :)

**Comment by pitsi** [comment]
Don't worry for the delays :)
It would be nice however if there was more positive feedback on the issue, because i was not the only one who had it, but just the one who first mentioned it.
