### ISSUE TITLE
Can't finish torrent download

### ISSUE THREAD

**Issue by antonsoroko** [elgatito/plugin.video.elementum#421]
## Current Behavior
After update elementum Can't finish torrent download - percentage is jumping around, after it says 100 you still have buffering issues, after stop and play again - percentage drops to 20.
Tried sevetsl times - see 2 logs.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used: 0.1.28

* Environment name and version:

* Operating System and version:

* Link to Kodi debug log:

spmc.log: https://paste.ubuntu.com/p/SyTSqgcNpN/
spmc.old.log: https://paste.ubuntu.com/p/PQR4z6bJRr/

**Comment by soulnull** [comment]
I have this happening too. Percentages are all over the place. Tried with disk caching and memory caching, same results. If you want another log, let me know, I'll generate one.

**Comment by MasterSoft24** [comment]
I confirm this behavior too

**Comment by soulnull** [comment]
Are you seeing this with disk caching, memory caching, or both? Trying to narrow it down...

**Comment by MasterSoft24** [comment]
I'm using a disk caching because I have too small onboard memory installed. As I suspect, The downloading stops after cache full filled

**Comment by elgatito** [comment]
It will be fixed in the next version. Only affected by file storage.

**Comment by soulnull** [comment]
Excellent, thank you.

**Comment by MasterSoft24** [comment]
How soon can we expect the release of the new version?

**Comment by elgatito** [comment]
Please, try v0.1.29.

**Comment by soulnull** [comment]
Looks good on my end.

**Comment by MichaelAndoid** [comment]
Same problem in v0.1.29 (Filestorage).

0.1.2.7 works ok.

**Comment by elgatito** [comment]
@MichaelAndoid log file is needed. And description what exactly you have.

**Comment by MasterSoft24** [comment]
v0.1.29 seems OK. At least, a playback aborting is fixed. But I found one more bug with an episodes list sorting and displaying.  I'll create new issue about it later.

**Comment by soulnull** [comment]
I'm still getting the randomly changing percentages, but it does not cause the playback to fail anymore. While the "failing to download" aspect of this appears to be fixed, I suspect the random percentages may be related to the original error since both started at the same time/only affect disk caches.. Log [here](https://paste.ubuntu.com/p/j9FQpfztR7/). This is "low priority", since it is cosmetic and doesn't appear to prevent the download from completing anymore.

**Comment by elgatito** [comment]
Original issue is fixed.
Any other issues should go to separate tickets.

**Comment by luispabon** [comment]
Thank you, f29 fixed it for me too.
