### ISSUE TITLE
Download still continue while the video already finished

### ISSUE THREAD

**Issue by burekas7** [elgatito/plugin.video.elementum#429]
I started to download an episode, the speed was good 6MB/s-8MB/s for torrents size of 3.5GB.
The percentage was increase too slow relate to the speed and torrent size, so I checked the video file in the folder, so I have noticed that it's already finished, but Elementum is still showing that it downloading.

I have also noticed the elementum.exe process was getting high memory usage and my laptop became hot, something happend there.

After restarting Kodi, it does show that it's 100% in the torrents list but it doesn't let me play it.

The torrent was added manully from file (Season torrent, so I select the wanted episode from there: Vikings S02E06: Vikings.S02E06.MULTI.1080P.X265.DTS.5.1.ONLY.mkv)

Kodi Log: (When it was "Downloading")
https://paste.ubuntu.com/p/BBtcYRD37H

Kodi Log: (After restart kodi and trying to play it from the torrent list)
https://paste.ubuntu.com/p/hV2hGDVcFk

Elementum 0.1.31
Kodi 17.6
Windows 10, 64 bit

**Comment by elgatito** [comment]
@burekas7 
Is it fixed in 0.1.35? Please, confirm.

**Comment by burekas7** [comment]
I'm cheking now the 0.1.35
But why the memory of elementum.exe is so hige? 724,000 K

**Comment by burekas7** [comment]
Another issue is the the file already done when I check it in my folder, but in kodi it's still show like it's still downloading (The percentage is not as should be according to the speed it was)


Log: https://paste.ubuntu.com/p/6BmRmS5jBp

**Comment by antonsoroko** [comment]
i also have this issue.
might be connected to #435

**Comment by elgatito** [comment]
@burekas7 please, check with 0.1.41. If still an issue - please, do a fresh log file.

**Comment by burekas7** [comment]
Hi,
I have tried with 0.1.41
But now the download doesn't even start after few minutes:

Kodi Log (With debug log):
https://paste.ubuntu.com/p/NtxGygXPHm

Just to mention, the episode was chosen from season pack (Both methods: 'Add Torrent' and through 'Search'.

**Comment by burekas7** [comment]
I have noticed also for a strange behaviour.
In the start, the actuall file size in windows browser show that the torrent is downloading so the file size increase each time. But after few hundreds of megabytes, it suddenly show like all the torrent downloaded (show the max file size), but in kodi the torrent still downloading and when running the video in a player, it doesn't have all the torrent yet. so how windows explorer shows it like it already downloaded. (And I don't talk about the 'Size' value, I talk about the 'actuall size on the disk')
