### ISSUE TITLE
Can't open torrent added via search from torrents list

### ISSUE THREAD

**Issue by antonsoroko** [elgatito/plugin.video.elementum#434]
Search for season pack via "torrent search", start download 1st episode for example, stop, go to torrents list, try to open torrent - unable to play error appears. After restart - still can't open torrent.

Btw i can "play" this torrent by open history item in search.
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:

* Environment name and version:

* Operating System and version:

* Link to Kodi debug log:

https://paste.ubuntu.com/p/S6pFHpTjYd/

**Comment by elgatito** [comment]
It should be fixed in the latest version. Please, confirm.

**Comment by antonsoroko** [comment]
Hi.
Still does not for season packs and also for torrents that was added via "search" menu (not from trakt).
If log file is needed i can add it later.
Thanks.

**Comment by antonsoroko** [comment]
looks like it does not work for any torrent that has more than 1 file

https://yadi.sk/d/7drr8A6i6KxKrA

also log files a huge now - a lot of messages :-)

**Comment by antonsoroko** [comment]
it's still an actual problem :-(

**Comment by elgatito** [comment]
@antonsoroko same as for #435 , please, add some new torrent, re-test and post a new log file. Thanks

**Comment by elgatito** [comment]
> 18:53:41.669 T:18446744072702916976   ERROR: InputStream: Error opening, plugin://plugin.video.elementum/play/Young%20Sheldon%20S02E17?episode=17&resume=5e262c9524862979544115736199bf9a0238557b&season=2&show=71728&tmdb=&type=episode

@antonsoroko Can you try with disabled InputStream plugin?
Also you can look in the log file, which url is trying to load, and try to open that url in browser/player, for example: 
```
http://127.0.0.1:65220/play/Young%20Sheldon%20S02E17?episode=17&resume=5e262c9524862979544115736199bf9a0238557b&season=2&show=71728&tmdb=&type=episode
```

**Comment by elgatito** [comment]
Cannot reproduce...
I have added option to select which file to play, in context menu of torrents list.

**Comment by antonsoroko** [comment]
Will try. Thanks.

But the root issue is that *any* torrent that was added via "search" menu can not be opened via torrent list. At least in my env.

**Comment by antonsoroko** [comment]
@elgatito 
у меня есть только InputStream Adaptive но он был выключен (для теста включил - ни на что не влияет).

>http://127.0.0.1:65220/play/Young%20Sheldon%20S02E17

для торентов что не открываются такого в логе нету даже.

но есть такое
```
23:43:14.687 T:18446744072736188784 WARNING: CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.elementum/play/The%20Good%20Doctor%20S03E01?episode=1&index=&resume=b62d8c4451775192499b4b5499662f363940bbc9&season=3&show=71712&tmdb=&type=episode
23:43:14.687 T:18446744072736188784   ERROR: Open - failed to open source <plugin://plugin.video.elementum/play/The%20Good%20Doctor%20S03E01?episode=1&index=&resume=b62d8c4451775192499b4b5499662f363940bbc9&season=3&show=71712&tmdb=&type=episode>
```
и если я делаю урл руками
```
curl -i 'http://192.168.178.63:65220/play/The%20Good%20Doctor%20S03E01?episode=1&index=&resume=b62d8c4451775192499b4b5499662f363940bbc9&season=3&show=71712&tmdb=&type=episode'
HTTP/1.1 302 Found
Content-Type: text/html; charset=utf-8
Location: http://192.168.178.63:65220/files/The%20Good%20Doctor%20S03E01%20Disaster%201080p%20AMZN%20Webrip%20x265%2010bit%20EAC3%205.1%20-%20Goki.mkv
Date: Wed, 16 Oct 2019 21:56:00 GMT
Content-Length: 163

<a href="http://192.168.178.63:65220/files/The%20Good%20Doctor%20S03E01%20Disaster%201080p%20AMZN%20Webrip%20x265%2010bit%20EAC3%205.1%20-%20Goki.mkv">Found</a>.
```

но в логе нету сообщений которые есть для торента добавленного через trakt, аля:
```
23:38:05.300 T:18446744072655931760   DEBUG: [plugin.video.elementum] Requesting http://127.0.0.1:65220/play/The%20Rookie%20S02E02?episode=2&index=&resume=7c144938dc25f5ace0bb2690dbf45f81cfae6103&season=2&show=79744&tmdb=&type=episode from ['plugin://plugin.video.elementum/play/The%20Rookie%20S02E02', '20', '?episode=2&index=&resume=7c144938dc25f5ace0bb2690dbf45f81cfae6103&season=2&show=79744&tmdb=&type=episode']
```

проблема только с торентами добавленными через поиск торентов (и если потом тот же торент пере-добавить через тракт - то начинает открываться).

надо смотреть разницу добавления через меню тракт и просто поиск.

**Comment by antonsoroko** [comment]
Такая же ситуация с торентом выбранным через "выбрать стрим" в меню сезона

**Comment by elgatito** [comment]
Please try the issue with default Kodi skin.

**Comment by antonsoroko** [comment]
Same issue:
torrent name is "12 стульев (1977).mkv"
https://paste.ubuntu.com/p/gb7KQVq9YD/

**Comment by elgatito** [comment]
@antonsoroko should be fine in 0.1.49.

**Comment by antonsoroko** [comment]
now it works for single file torrents - thank you
but fails for season pack - looks like i had the same issue when i created initial version of this issue 
https://github.com/elgatito/plugin.video.elementum/issues/558

**Comment by elgatito** [comment]
@antonsoroko please, check with 0.1.50.

**Comment by antonsoroko** [comment]
👏 👏 👏 
Thank you very much!
