### ISSUE TITLE
[Feature] Populate watched from Trakt

### ISSUE THREAD

**Issue by hoshsadiq** [elgatito/plugin.video.elementum#47]
Currently if you watch a show/movie it updates Kodi to say it's been watched, and from there something seems to pick it up and update Trakt's watch status. There's nothing that does the inverse though (if you mark a movie on trakt as watched, it won't show this on Kodi). It would be nice to have this as a two way sync.

**Comment by elgatito** [comment]
Should be fixed with 0.0.29 which introduces two-side sync between Kodi and Trakt.

**Comment by burekas7** [comment]
It's still not working:
https://github.com/elgatito/plugin.video.elementum/issues/53
