### ISSUE TITLE
Season 27 of anime Doraemon not opening

### ISSUE THREAD

**Issue by movianlost** [elgatito/plugin.video.elementum#736]
I have tested the latest Elementum update and it fixes my previous reported issues.

I decided to open a new issue because this is related to Elementum not Burst.

Issues:

1. When I click on anime Doraemon season 27, it doesn't open and it shows an error:` Elementum Internal Server Error`, using a similar addon, Themoviedb Helper, I can click on season 27 and play it with Elementum without any issue.
2. In the same show, Elementum is sending payload with inconsistent episode numbers, here is an example of what I click on and what Elementum sends.

The first is the episode I click on -> this is what Burst receives, I notice the value of absolute_number in the payload
 
```
S25E9->S25E9 payload has absolute_number:0
S25E10->S25E1704 payload has absolute_number:1704

S24E9->S24E1658 payload has absolute_number:1658
S24E10->S24E10 payload has absolute_number:0
S24E11->S24E1660 payload has absolute_number:1660
```

Here is the log from the moment I started testing.
I clicked on S25E9 then S25E10 then went back and tried to enter S27

https://pastebin.com/raw/PWc5anzN

**Comment by antonsoroko** [comment]
@movianlost 

this particular issue (`Elementum Internal Server Error`) should be fixed by https://github.com/elgatito/elementum/commit/a9010a9fd93f4babcc8b6ce538489799ec975527

i am not talking about `absolute_number` since it looks like a separate issue.

**Comment by elgatito** [comment]
Issue should be already fixed.

**Comment by movianlost** [comment]
@elgatito I tested the latest version and `Elementum Internal Server Error` is fixed and season 27 is working fine.

However, the second issue is still not fixed, can you read my original comment I have described it there where the payload sometimes it send the absolute number and sometimes not

**Comment by antonsoroko** [comment]
@movianlost  let's keep separate issues in separate tickets, please.
