### ISSUE TITLE
[Bug] Regarding the "Show unaired episodes" setting

### ISSUE THREAD

**Issue by burekas7** [elgatito/plugin.video.elementum#834]
Hi,

When the setting: **"Kodi library -> Show unaired episodes"** is **disabled**:
The unaired episode still takes into account, and the season presented as **Unwatched** status.

- Case 1 - Setting is **disabled**:
![image](https://user-images.githubusercontent.com/13424257/136859738-12ea4ae0-c451-4af0-af3a-7a28eb0da4c7.png)
- Case 2 - Setting is **enabled**:
![image](https://user-images.githubusercontent.com/13424257/136860113-48729d06-0ce5-4526-b5df-5550dcd8878b.png)

On both cases:
- Shows:
![image](https://user-images.githubusercontent.com/13424257/136859605-624e49e7-1ac3-4426-bfa7-ee69e41d1875.png)
- Seasons:
![image](https://user-images.githubusercontent.com/13424257/136860131-a86618d4-c577-4b33-ae48-70583ea8ad6f.png)

**I expect that:**
- When this setting is **disabled**, the season should be presented as **"Watched'** as long as all the episodes have been watched up to the unaired episode.
- When this setting is **enabled**, the season should be presented as **"Unwatched"** due to the unaired episode which is of course marked as "Unwathced".

---
**[Request]**
In addition, a **request** regarding the **"unaired episodes"**:
Please mark the unaired episodes in the Trakt/TMDB lists with a different style or color (As it done for example in the Trakt > My Progress), so it will be more clear that it is an unaired episode.

Thanks.

---
Elementum 0.1.83
Kodi 19.2
Skin Titan MOD
Windows 10, 64bit

**Comment by elgatito** [comment]
@burekas7 Should be fixed with the latest version.

**Comment by burekas7** [comment]
@elgatito 
Hi,
It's hard to find a tv shows with unaired episodes these days when almost every tv show releases all their episode at once.

But it seems that the bug still exists in 0.1.86:
For example: Strange Things  - Season 4
* Kodi library -> Show unaired seasons" is disabled.
* Kodi library -> Show unaired episodes" is disabled.

All the episodes there are currently defined as unaired,
But it shows the this tv show is in 'unwatched' status, when I go into the season 4, it shows wmpty list, because "Show unaired episodes" is disabled.
I think you probably fixed only the "Show unaired episodes", maybe there is a problem also with "Show unaired seasons"

![image](https://user-images.githubusercontent.com/13424257/149525398-0b842c0c-7cc0-45c2-8e1e-e5dfbbf16175.png)

**Comment by burekas7** [comment]
@elgatito 
Another issue regarding this issue

I don't think it relates only to the "unaired episode" option.
For example: Black Mirror S04 (Which already released in 2017)

The current watched status tags should be:
- 2 unwatched seasons
- 2 unwatched episodes

But instead it shows:
- 5 unwatched seasons
- 6 unwatched episodes
It count all the seasons/episodes when there is at least one unwatched season or episodes instead count only the unwatched.

![image](https://user-images.githubusercontent.com/13424257/152262548-40cd2778-dd7c-40cb-84df-70519acb4bc6.png)

![image](https://user-images.githubusercontent.com/13424257/152262626-e01b3867-b86d-4f5b-bfb8-b63ee2dcd95e.png)

![image](https://user-images.githubusercontent.com/13424257/152262726-657607fa-db71-4553-a1f8-fa6f219079d4.png)

Kodi log:
https://paste.ubuntu.com/p/NCKTGBtWDb

Elementum: 0.1.86
Kodi 19.3

**Comment by burekas7** [comment]
@elgatito 

Hi,
This bug in the last comment still exists in 0.1.98, Kodi 20
The left episodes is wrong in the seasons view, but correct in the TV Shows collection view.

**Comment by antonsoroko** [comment]
>The left episodes is wrong in the seasons view, but correct in the TV Shows collection view.

can you define more clearly what do you mean by "seasons view" and by "TV Shows collection view"?
for example, you can use full paths to describe what you mean, like "Shows" --> "Tratk > My lists" ---> "...".

**Comment by burekas7** [comment]
> > The left episodes is wrong in the seasons view, but correct in the TV Shows collection view.
> 
> can you define more clearly what do you mean by "seasons view" and by "TV Shows collection view"? for example, you can use full paths to describe what you mean, like "Shows" --> "Tratk > My lists" ---> "...".
> 
> also, what skin do you use?

TV Shows collection view => Trakt -> TVShows -> Collection -> TV shows list
TV Shows seasons view => Trakt -> TVShows -> Collection -> *TV SHOW NAME* -> Seasons list

**Comment by antonsoroko** [comment]
>Trakt -> TVShows -> Collection

do you mean "TV Shows" ---> "Trakt > My Collection" ---> "list of shows here"?
your "titles" differs from elementum's "titles" so it is a bit confusing.

>Skin: Titan

this is not a standard skin. also looks like there are many variations of that skin. care to provide a link?

**Comment by burekas7** [comment]
> > Trakt -> TVShows -> Collection
> 
> do you mean "TV Shows" ---> "Trakt > My Collection" ---> "list of shows here"? your "titles" differs from elementum's "titles" so it is a bit confusing.
> 
> > Skin: Titan
> 
> this is not a standard skin. also looks like there are many variations of that skin. care to provide a link?

1. Yes. It also happens in Lists.
There tags in Seasons show wrong count, it counts all the episodes and not the unwatched episodes. While in the TV Shows lists the tag show the correct number of unwatched episodes. (The images above shows it, for example 6 instead of 2)

2. I don't think it's a skin issue, unless this data isn't provided by Elementum.
Link for the repo zip installation:
https://github.com/Fuchs246/repository.fuchs246/tree/main/nexus/repository.fuchs246

**Comment by antonsoroko** [comment]
@burekas7 just to be clear, do you have "Show number of unwatched episodes in Shows/Seasons" option enabled?
also, when i implemented this feature i remember there were issues with titan skin because of how titan skin use (calculate) data (numbers) provided by elementum. it worked ok with standard skin.

see https://github.com/elgatito/elementum/pull/67 and the end of https://github.com/elgatito/plugin.video.elementum/issues/684

**please test with some other skin** - if you still have the issue - then i will try to see what could cause this.
i am asking to test since there were no changes to this code (except that ShowUnairedEpisodes check that you asked for, but it actually does nothing, since code count **watched** episodes, and unaired episode is not supposed to be watched so it was ignored anyway).

also, make sure that episodes also **marked as watched in Trakt website**, it might be that you marked them watched only locally in Kodi.

**Comment by antonsoroko** [comment]
(
on a side note: where ShowUnairedEpisodes could be used is for calculating total number of episodes. for season TMBD gives list of all episodes in season (not count but list), so i used that number in code. but we could actually manually check air date for every episode and see if user want to see all episodes or only aired episodes. and total number also affects unwatched number (we count watched number and then subtract it from total to get unwatched). BUT for show this will not work, since for show TMBD gives total number of episodes as number. so we will have different info in season and show view. of course we could then ask for info about each season and check every episode for air date - but this will be extremely slow for any big Trakt list.
thus, i am not sure that we should use ShowUnairedEpisodes at all for total/unwatched/wathched numbers. this option is about "showing" not counting. for counting it will bring a lot of slowness.

anyway, it is not connected to issue you are having. it is just thinking out loud about possible enhancements. 
)

**Comment by burekas7** [comment]
@antonsoroko 
I don't talk about "unaired" episodes for the second issue here.
The "unaired" episodes was related for the first/original issue that I think was fixed.

Now I'm talking about "aired" unwatced episodes that isn't calculated/counted properly as mentioned.
And as said, you get the internal data different between Shows view and Seasons view, and that makes the problem.
You actually don't have any information on the "unwatched/watched" episodes when you are in Seasons view? If so, how does it work in other skins? (I haven't check it yet by the way)

"Show number of unwatched episodes in Shows/Seasons" is enabled.
Trakt data is updated in their site.

**Comment by antonsoroko** [comment]
I am afraid that you understood my comments incorrectly. My point was to give explanation of how code works and why it works like this and why I have not used ShowUnairedEpisodes in code for counting total number of episodes (total number, not watched number). Not to make some polemic.

>I don't talk about "unaired" episodes for the second issue here. The "unaired" episodes was related for the first/original issue that I think was fixed.

I have not said that you were talking about unaired, I said that mentioned fix did nothing in my opinion. Explanation is above.

>You actually don't have any information on the "unwatched/watched" episodes when you are in Seasons view? 

Again, I never said that. We count number of watched episodes, and derive number of unwatched episodes by subtracting from total number of episodes. More detailed explanation is above.
The thing to remember is that TMDB gives us number of total episodes and it includes aired and unaired episodes. Again, more details why this is important - above.

>how does it work in other skins?

I provided links with relevant info. You could try to read them :-) For example - https://github.com/elgatito/plugin.video.elementum/issues/684#issuecomment-858507526

We calculate numbers and then provide those numbers to kodi. Then skin read those numbers from kodi and does its own calculations/logic and show numbers.

>I haven't check it yet by the way

Please check. from my comment above:
>please test with some other skin - if you still have the issue - then i will try to see what could cause this.

Also please specify with which show and season and last episode you have issue. If i will have time i will try to reproduce the issue with your specific conditions (skin and show and language and etc).

**Comment by burekas7** [comment]
@antonsoroko 

It happens with any TV Show.

Fresh example: Fargo

- Titan:
TV Shos view:
The episodes tag shows "1" which is correct, it doesn't count the "special" season episodes.
![image](https://github.com/elgatito/plugin.video.elementum/assets/13424257/f5f2fe00-88f0-438c-ad2c-ca3e65cab0fe)

Seasons view:
(Shows "10" which is wrong, probably it's the total amount of the season episodes, no matter if "watched/unwatched", it counts also the "unaired" I guess)
![image](https://github.com/elgatito/plugin.video.elementum/assets/13424257/4a0d7ceb-7e6b-4ae9-b9a1-40b2879d5888)

Episodes view:
(You can see, there is only one unwatched episode)
![image](https://github.com/elgatito/plugin.video.elementum/assets/13424257/56ced81b-d32d-4ade-9707-a186496a74b7)

---------
Estuary test:
TV Shos view:
![image](https://github.com/elgatito/plugin.video.elementum/assets/13424257/c5136d00-a838-421a-bd92-5af3a250e53e)

Seasons view:
(They do have any episodes tag in this view)
![image](https://github.com/elgatito/plugin.video.elementum/assets/13424257/37bfc1fd-c284-49fb-b531-fc89eeb5f3ab)


----------
Estouchy test:
They don't have any episodes tag.

**Comment by antonsoroko** [comment]
>2022-02-03 02:38:20.965 T:20516 WARNING <general>: [plugin.video.elementum]   ForceUseTrakt: true,

from your old log. which is Use Trakt information in Trakt lists" option.
so that's why you get show's (about season - see below) "total number of episodes" as "total number of aired episodes".
trakt api gives "total number of aired episodes", tmdb api gives "total number of episodes".
but as i said before, to manually count show's "total number of aired episodes" for tmdb we would need to go over all episodes of all seasons, which could be noticeably slow for big lists. it is already relatively slow if ForceUseTrakt is enabled.

btw, good skin to test all those things like watched/unwatched/total episodes, total seasons, network/production logos and etc, is standard [Aeon Nox: SiLVO](https://kodi.tv/addons/nexus/skin.aeon.nox.silvo/).

>it counts also the "unaired" I guess

for seasons we always use TMDB (even with ForceUseTrakt) and tmdb api gives only "total number".

**Comment by burekas7** [comment]
@antonsoroko 
So if I will disable "Use Trakt information in Trakt lists" option the problem will be also with TV Shows view, which is bad.

Why can't we use Trakt info also for Seasons view?

Are you using this api?
https://trakt.docs.apiary.io/#reference/seasons/summary/get-all-seasons-for-a-show
`https://api.trakt.tv/shows/id/seasons`

Why don't you use it also for the "Seasons" view?

The response should be something like this, which includes data for all the seasons.
So you have the "aired_episodes" of each season and you can use it and subtract from it the "watched" episodes of each season.
Exactly as you calculate it for TV Shows view I guess.

```
[
  {
    "number": 0,
    "ids": {
      "trakt": 1,
      "tvdb": 137481,
      "tmdb": 3627
    },
    "rating": 9,
    "votes": 111,
    "episode_count": 10,
    "aired_episodes": 10,
    "title": "Specials",
    "overview": null,
    "first_aired": "2010-12-06T02:00:00.000Z",
    "udpated_at": "2010-12-07T01:023:00.000Z",
    "network": "HBO"
  },
  {
    "number": 1,
    "ids": {
      "trakt": 2,
      "tvdb": 364731,
      "tmdb": 3624
    },
    "rating": 9,
    "votes": 111,
    "episode_count": 10,
    "aired_episodes": 10,
    "title": "Season 1",
    "overview": "Season 1 overview.",
    "first_aired": "2011-04-09T02:00:00.000Z",
    "udpated_at": "2010-12-07T01:023:00.000Z",
    "network": "HBO"
  },
]
```

Regarding the skin, I don't think that Elementum should be good for only one skin or few.
But anyway as you said, it's not a skin problem, it's a logic issue and the difference between Trakt and TMDB.

**Comment by elgatito** [comment]
Here is what I think is supported by `ListItem` in Kodi: https://kodi.wiki/view/InfoLabels

And properties, that are probably related to described issues:

<html>
<body>

ListItem.Property(TotalSeasons) | Shows the total number of seasons for the currently selected tvshow |  
-- | -- | --
ListItem.Property(TotalEpisodes) | Shows the total number of episodes for the currently selected tvshow or season |  
ListItem.Property(WatchedEpisodes) | Shows the number of watched episodes for the currently selected tvshow or season |  
ListItem.Property(UnWatchedEpisodes) | Shows the number of unwatched episodes for the currently selected tvshow or season |  
ListItem.Property(NumEpisodes) | Shows the number of total, watched or unwatched episodes for the currently selected tvshow or season, based on the the current watched filter.


</body>
</html>

Do I understand correctly that we show wrong number of episodes in different situations across browsing show? 
It is hard to follow the thread already.

**Comment by burekas7** [comment]
@elgatito 
Yes, you get it correctly.

You can focus on the last example I show here with "Fargo".
In Shows menu -> 1 unwatched episodes left which is correct.
In Seasons menu -> 10 unwatched episodes left in the last season ("Year Five") which is wrong. It should be also "1".

We found that problem that in "Seasons" menu, the number is taken from TMDB, that return "10" which is the total amount of episodes in this season (Include "unaired" episodes).

It should be act in "Seasons" menu (for each season), the same as it works for "Shows" menu.
The logic should be (For a season): Aired episodes - Watched Episodes (or) Unwatched episodes from Aired episodes.

**Comment by antonsoroko** [comment]
@burekas7 
>Are you using this api?

first of all - you confuse "me" and "elementum's code".

elementum uses this api (you can search code in gihub, you know). just not for that particular use case.

>Why don't you use it also for the "Seasons" view?

because, as i wrote in your other issue:
>logic for tmdb and trakt is different, probably because it was written by different people in different times.

i added this feature just for fun, i have not had intention to refactor all the trakt/tmdb code, considering that i am not very familiar with that code, and i am not a professional developer. so i just added new feature to existing "code places". there was no "code place" for trakt seasons.

>Regarding the skin, I don't think that Elementum should be good for only one skin or few.

i meant that this skin is kind of a "reference" skin (because it has a lot of UI features and it is "standard" skin), not "Elementum should be good for only one skin".

---

1. i think i found a bug. 
2. if we want consistent data for tmdb and trakt source - then some refactoring would be needed anyway -  to make trakt use trakt info (instead of tmdb) for seasons view and to make tmdb count aired episodes (it is lame that their api does not provide such number).

**Comment by antonsoroko** [comment]
@elgatito 
to summarize: we count numbers and then we set those custom labels.
but depending on chosen info source (trakt/tmbd) we use different numbers for TotalEpisodes (all vs aired) - which is not a bug, but can be improved (we can try to count "aired" for tmdb).
and for tmdb there is a real bug with counting episodes - looks like episodes list for *tmdb.Season and *tmdb.Show are empty. But in my cache it still have some non empty list of episodes for some shows, not sure how it happened.

**Comment by elgatito** [comment]
@antonsoroko There is no endpoint for Trakt seasons list. There is only one for TMDB seasons. So to get from Trakt show to list of seasons you need to get anyway TMDB information and then list seasons based on TMDB data.
I am not even sure Trakt will have enough information for seasons list view.

**Comment by antonsoroko** [comment]
@elgatito 

>There is no endpoint for Trakt seasons list. 

what do you mean exactly? there is
https://trakt.docs.apiary.io/#reference/seasons/summary/get-all-seasons-for-a-show?console=1
and i added it last time, but only for counting sake. 
https://github.com/elgatito/elementum/blame/master/trakt/shows.go#L213

but i think we can use it for seasons list view.
example of output: https://paste.ubuntu.com/p/yXK2zgWTMM/

**Comment by elgatito** [comment]
@antonsoroko 

> what do you mean exactly? there is

In Elementum there is no endpoint for list of Trakt seasons.
We have only this: `show.GET("/:showId/seasons", ShowSeasons)`

**Comment by elgatito** [comment]
@burekas7 We were always taking numbers based on information provided by TMDB (number of episodes in a season/show).

I've pushed a change to count based on episodes information. Looks more precise, but it will slow down loading, because we will need to get information about every season of a show to know dates of episodes and check each episode if it is watched or not.

**Comment by antonsoroko** [comment]
oh, so we use trakt info only for "trakt lists", **literally** only for "trakt lists".

**Comment by elgatito** [comment]
@antonsoroko Yes. 

To make native Trakt lists you would need to make Seasons list page and Episodes list page. 
Nothing bad with that, but for me it does not cost the time spent on it.

**Comment by antonsoroko** [comment]
@elgatito 

>I've pushed a change to count based on episodes information. Looks more precise, but it will slow down loading, because we will need to get information about every season of a show to know dates of episodes and check each episode if it is watched or not.

that's how i had it in my mind. but while i was tried to made up my mind - you wrote the whole code :-) you are awesome.
and i also warned **burekas7** about slowness.

i also left some comments about in commit.

**Comment by burekas7** [comment]
@elgatito 
Just to be sure I understood it correctly.

1) The number in Trakt -> My Collection (Tv Shows) is correct since it's a "Trakt list" so you are using the Trakt API info to calculate the unwatched episodes since Trakt does have info on the "Aired ?
2) The number in Trakt -> My Collection (Tv Shows) -> Seasons is incorrect since it's not a "Trakt list", it's internal Elementum list, so you are using the TMDB API info which doesn't have info about the "Aired episodes", so you can't do the calculation?
3) Why can't you use the data from Trakt info on the TV Shows view and pass it to the Seasons view? So you can do the calculation, instead of using the TMDB again for each season and make it slow.
4) By the way, TV Shows have 3-5 seasons on average, making an api call (TMDB) for each season doesn't should takes long time, or I'm missing something in understanding the logic

https://trakt.docs.apiary.io/#reference/seasons/summary/get-all-seasons-for-a-show
`https://api.trakt.tv/shows/id/seasons`

**Comment by elgatito** [comment]
@burekas7 

> The number in Trakt -> My Collection (Tv Shows) is correct since it's a "Trakt list" so you are using the Trakt API info to calculate the unwatched episodes since Trakt does have info on the "Aired ?

There is one method that is rendering shows for any Trakt lists (My collection, Trending, etc). 
So it should be the same in those places.

If TMDB information in Trakt lists is disabled - it will use only Trakt information. They have a special field "AiredEpisodes", but it is also not always precise, as we have caching and you can have different setting for a delay after showing aired episodes.

> The number in Trakt -> My Collection (Tv Shows) -> Seasons is incorrect since it's not a "Trakt list", it's internal Elementum list, so you are using the TMDB API info which doesn't have info about the "Aired episodes", so you can't do the calculation?

TMDB does not have a single field for number of Aired episodes, you need to loop through all episodes and count. Also if you have enabled hiding Special seasons - you cannot use that field, you need to re-calculate.

> Why can't you use the data from Trakt info on the TV Shows view and pass it to the Seasons view? So you can do the calculation, instead of using the TMDB again for each season and make it slow.

Because we use Trakt -> TMDB relation everywhere. Even from code side that is a huge change to use Trakt information from TMDB.

> By the way, TV Shows have 3-5 seasons on average, making an api call (TMDB) for each season doesn't should takes long time, or I'm missing something in understanding the logic

Here few requests, there few requests, then Fanart request as well can follow, and maybe Trakt request and each takes time.

**Comment by burekas7** [comment]
@elgatito 
So if we sum up,
At that moment, there is no way to figure out the correct unwatched episodes for each season on Seasons view, right? 
So actually there is no point in displaying the number right now, since it's confusing showing the total amount of episodes of the season when you expect that it will present the 'unwatched' amount as it actuall does on TV Shows view (TV Shows -> "Trakt - My Collection")

Or there is any other solution you can think of that won't slow down the process.

**Comment by antonsoroko** [comment]
@burekas7 
>At that moment, there is no way to figure out the correct unwatched episodes for each season on Seasons view, right?

no. you are sure that you have read all the last comments??? have not you seen this?

>I've pushed a change to count based on episodes information.

the change is already made. it might be slower than it used to be, but still works fine. at least for me.

or maybe you confused about how we calculate unwatched. obviously we can not count unwatched since you can not count something that does not exist.
thus we count total (and there was cosmetic issue about all vs aired for tmdb source - fixed), then we count watched (there was issue for tmdb season - fixed), then we subtract watched from total to get unwatched.
so now it works ok.

however i did find some small issues, but i already made a fix, but have not pushed it yet. after it will be pushed - counting of everything should be correct for any cases.

if you want to test it - here is a test build for your platform (windows x64 iirc) - put it into `.kodi/addons/plugin.video.elementum/resources/bin/` or similar.
https://disk.yandex.ru/d/Z9veYtA9y1CU9g

**Comment by burekas7** [comment]
@antonsoroko 
Thanks.

Now it's working for Seasons view:
"2" unwatched episodes instead of "10" before.
![image](https://github.com/elgatito/plugin.video.elementum/assets/13424257/cfdf51a0-a290-42b1-84e1-be3d3b1bee17)
![image](https://github.com/elgatito/plugin.video.elementum/assets/13424257/7360a786-c69e-449e-952d-ca022be52bdc)

But now the TV Shows view doesn't show the correct number.
It shows "1" instead of "2".
![image](https://github.com/elgatito/plugin.video.elementum/assets/13424257/5cae290c-0bca-4209-8bb8-e21adbb5258e)

**Comment by antonsoroko** [comment]
@burekas7 it works good for me. but on your screenshot i do not see number of all episodes - which is crucial to understand the numbers - see above how we calculate unwatched.
also, can it be that you just marked episode as watched in trakt and then opened shows view? then most likely you just  have "local caching" delay.

please do this:
0. enable skin that shows you also total number of episodes, like [Aeon Nox: SiLVO](https://kodi.tv/addons/nexus/skin.aeon.nox.silvo/). 
1. enable forceusetrakt
3. go to shows => "anything with trakt in name" - see numbers for shows - this path will use trakt as info
4. got to show -=> search - see numbers for shows - this path will use tmdb as info
5. share results.

**Comment by elgatito** [comment]
@burekas7 Had to spend some time trying to collect all dependencies for Titan MOD skin, but was able to run it finally.

Checked lists of shows in My Collection and Trending, with and without enabled TMDB replacing Trakt information. Numbers looks the same (with latest code changes).

**Comment by antonsoroko** [comment]
@elgatito i do have small issue with "total number of episodes of show" from trakt, but only or show that have new episode aired today. https://trakt.tv/shows/reacher/seasons/2

but this looks like caching issue, right?

**Comment by elgatito** [comment]
@antonsoroko 

> but this looks like caching issue, right?

I don't have issues with counts, but it can be an issue from caching. We cache for 7 days seasons and episodes.

**Comment by antonsoroko** [comment]
>but it can be an issue from caching. We cache for 7 days seasons and episodes.

i meant exactly that.
if i comment out this line https://github.com/elgatito/elementum/blob/6aea37dab272b523d6ec42dd75ef123031e388d6/trakt/shows.go#L630
then it is ok.

**Comment by antonsoroko** [comment]
@burekas7 so we do not see any issue, apart maybe from not updated cache on your/mine elementum caching database.

1. please follow all steps https://github.com/elgatito/plugin.video.elementum/issues/834#issuecomment-1867695522 and share results
2. then clear "trakt cache" in advanced setting of elementum and do test again and share results.

**Comment by antonsoroko** [comment]
@elgatito btw, for trakt, instead of counting everything manually, we can try to use https://trakt.docs.apiary.io/#reference/shows/watched-progress/get-show-watched-progress?console=1
we already have code https://github.com/elgatito/elementum/blob/6aea37dab272b523d6ec42dd75ef123031e388d6/trakt/shows.go#L810 , so we can move it into separate function and use it in `watchedEpisodesNumber` to get `Completed` property. does it sound reasonable? 
the only thing is caching again. 7 days is to much.

also since `Only aired episodes are used to calculate progress. Episodes in the future or without an air date are ignored.` it should be ok even if user makred as watched unaired episode.
Also for "total" we use "aired" too.
so numbers should be always aligned.

**Comment by elgatito** [comment]
@antonsoroko 

> instead of counting everything manually, we can try to use https://trakt.docs.apiary.io/#reference/shows/watched-progress/get-show-watched-progress?console=1

That will work only if you have Trakt connected and properly filled with progress information.
I can't see how it makes counting better if we already have precise manual counting instead of relying on API responses?

**Comment by antonsoroko** [comment]
@elgatito what i meant is that such change will reduce amount of code. nothing more :-)
just less code - less error, i think.

but you are right about "only if you have Trakt connected", i missed that.
thus we can not use it.

then i believe we done with code changes and let's wait for results of tests from **burekas7**.

**Comment by burekas7** [comment]
@elgatito @antonsoroko 
Thanks.
You were right, clearing Trakt cache fixed the unwatched episodes count also in TV Shows view.
Now all is good (Tested with the latest temp version @antonsoroko put here)

What is the logic that exists today regarding automatic Trakt cache cleaning?
Every start of Elementum? 
Every few days? If so, maybe it's worth shortening it.
Or even clear it on each time when player finishes to play a video (not on each stop of course)...

**Comment by antonsoroko** [comment]
@burekas7 there are many caches in elementum. also, it would be more correct to say that we not not clear them, we update them. **every time** when we do request (like "get seasons") we check if we have "response" in cache and if cache is still valid.

the cache you had issue with is the cache of seasons - it does not make sense at all to update it every time user finished playing video request, since episodes usually come out every week (or all at once). 
also if you update cache every time - what is the point of cache? :-)
also we would not be able to update it anyway, because this cache is not related to episodes you watch, it is connected to lists (i repeat, it is connected not to show, but to list of shows - big difference).

also, make sure you are not confused about how unwatched is calculated. please read above the exaplation. main point is that it is calculated based on other numbers.

very sad that you ignored what i wrote and you did not do what i asked you to do (you did not share results, and i guess you did not change skin for test). if you would have done it - you would see the real reason. with proper skin you would see that numbers of total and aired were old for list of shows. 

about for how long we keep using cached info (instead of "live" info), see https://github.com/elgatito/elementum/blob/6aea37dab272b523d6ec42dd75ef123031e388d6/cache/types.go#L97

usually, as elgatito mentioned above, it is 7 days (`GeneralExpire = 7 * 24 * time.Hour`).

but if you use kodi rarely, then it can be that you ran kodi just before new episode was aired and then you have misaligned cache for some data. **it does not matter for everything else (like name of show, id of show, images and etc), but matters for total/aired numbers.**
the problem here is that this feature (to have those 3 numbers) is not mega useful, but very capricious.
it would be stupid to change whole caching systems just because of it.

the only "simple" solution i see is to neglect numbers from Trakt (i mean this `aired_episodes` field, for example do https://trakt.docs.apiary.io/#reference/users/list-items/get-items-on-a-personal-list?console=1 with `https://api.trakt.tv/users/qazerr/lists/test/items/shows?extended=full`) and calculate them manually like we do for tmdb.

**Comment by burekas7** [comment]
@antonsoroko 

`try this build: https://disk.yandex.ru/d/Z9veYtA9y1CU9g`

This version is not good, it shows "6" unwatched episodes.
The previous build was good.

**Comment by burekas7** [comment]
By the way, regarding the Trakt cache issue,
I found that we already discussed on it on this issue:
https://github.com/elgatito/plugin.video.elementum/issues/680

There I was talking aboud Movies, when I add a movie in Trakt site but because it always show the list from cache, the movie isn't shown unless I clear it in order to force refresh the list.

**Comment by antonsoroko** [comment]
@burekas7 that scenario is **very different** - please re-read my comment https://github.com/elgatito/plugin.video.elementum/issues/680#issuecomment-802866135 it has detailed info, i dunno why you confused again.
if you changed list - we can ask trakt about this via api, so then we can update cache without waiting for cache to expire.
but there is no simple way to know if a new episode of a show that is inside of your list was aired. if you are willing to write some tricky code that would somehow calculate this event - please do.

**Comment by antonsoroko** [comment]
@burekas7
>This version is not good, it shows "6" unwatched episodes.

next time please provide log file.

>Why did you make a new build by the way, it was good already, I just clear Trakt cache and it fixed the number in TV Show view.

because clearing cache every time is not a solution. and since different shows air at different days -  you would need to clear cache very often.

---

i found the issue with time parsing, trakt and tmdb use different format. i will fix.

**Comment by burekas7** [comment]
@antonsoroko 
If I get it right, with the previous build you made, if a new episodes was aired, I would still get it as "2" as long as no new cache clearing was made?

What was your solution in the new build?
Do you still need the log when entering to the Trakt - My Collection?

And thanks.
I will wait for you updates.
Tell me if you need any info from me.

**Comment by burekas7** [comment]
> @burekas7 that scenario is **very different** - please re-read my comment [#680 (comment)](https://github.com/elgatito/plugin.video.elementum/issues/680#issuecomment-802866135) it has detailed info, i dunno why you confused again. if you changed list - we can ask trakt about this via api, so then we can update cache without waiting for cache to expire. but there is no simple way to know if a new episode of a show that is inside of your list was aired. if you are willing to write some tricky code that would somehow calculate this event - please do.

And it's pretty the same though. 
since I made changes in Trakt site, Elementum didn't know about it unless I clear the Trakt cache. 
I think we should add an option in the setting to schedule time for clear Trakt cache with options such as (Default, On Kodi start, Every day, once a week, custom days value....)
Unless you have any other idea.

**Comment by antonsoroko** [comment]
>Do you still need the log when entering to the Trakt - My Collection?

no.

>What was your solution in the new build?

as i wrote above:
> the only "simple" solution i see is to neglect numbers from Trakt (i mean this aired_episodes field, for example do https://trakt.docs.apiary.io/#reference/users/list-items/get-items-on-a-personal-list?console=1 with https://api.trakt.tv/users/qazerr/lists/test/items/shows?extended=full) and calculate them manually like we do for tmdb. again it will make things just a little bit slower.

so i just did it.
but then after you reported issue

>i found the issue with time parsing, trakt and tmdb use different format. trakt also adds time, but unfortunately golang is not smart enough to just ignore it if we do not need it.

**Comment by antonsoroko** [comment]
@burekas7 
>since I made changes in Trakt site, Elementum didn't know about it unless I clear the Trakt cache or it's done autoatically every 7 days as you said.

not true. read my comment - looks like you still did not. as i wrote it will be 5 minutes maximum or restart. unless you changed it.
in your old log
>2022-02-03 02:38:20.975 T:20516 WARNING <general>: [plugin.video.elementum]   TraktSyncFrequencyMin: 50,

so it is 50 minutes for you and you did it to yourself voluntarily :-)
if nowadays you have it as 5 - then create a bug please.
it works for me - just tested, i opened kodi, i added show to list on website, no new show, waited 5 minutes, new show added.

**Comment by antonsoroko** [comment]
@burekas7

>Do you still need the log when entering to the Trakt - My Collection?

no.

>What was your solution in the new build?

as i wrote above:
> the only "simple" solution i see is to neglect numbers from Trakt (i mean this aired_episodes field, for example do https://trakt.docs.apiary.io/#reference/users/list-items/get-items-on-a-personal-list?console=1 with https://api.trakt.tv/users/qazerr/lists/test/items/shows?extended=full) and calculate them manually like we do for tmdb. again it will make things just a little bit slower.

so i just did it.
but then after you reported issue

>i found the issue with time parsing, trakt and tmdb use different format. trakt also adds time, but unfortunately golang is not smart enough to just ignore it if we do not need it.

**Comment by antonsoroko** [comment]
@burekas7 
>since I made changes in Trakt site, Elementum didn't know about it unless I clear the Trakt cache or it's done autoatically every 7 days as you said.

not true. read my comment - looks like you still did not. as i wrote it will be 5 minutes maximum or restart. unless you changed it.
in your old log
>2022-02-03 02:38:20.975 T:20516 WARNING <general>: [plugin.video.elementum]   TraktSyncFrequencyMin: 50,

so it is 50 minutes for you and you did it to yourself voluntarily :-)
if nowadays you have it as 5 - then create a bug please.
it works for me - just tested, i opened kodi, i added show to list on website, no new show, waited 5 minutes, new show added.

**Comment by burekas7** [comment]
So what is the difference between "Synchronize frequency of Trakt" (According to the settings) and "Clear Trakt cache" which is 7 days that we mention here regarding the episodes count?

I don't want to discuss on the issue of https://github.com/elgatito/plugin.video.elementum/issues/680 here, but the "Synchronize frequency of Trakt" action didn't affect on it unless I did Clear cache.

**Comment by burekas7** [comment]
> @burekas7
> 
> > Do you still need the log when entering to the Trakt - My Collection?
> 
> no.
> 
> > What was your solution in the new build?
> 
> as i wrote above:
> 
> > the only "simple" solution i see is to neglect numbers from Trakt (i mean this aired_episodes field, for example do https://trakt.docs.apiary.io/#reference/users/list-items/get-items-on-a-personal-list?console=1 with https://api.trakt.tv/users/qazerr/lists/test/items/shows?extended=full) and calculate them manually like we do for tmdb. again it will make things just a little bit slower.
> 
> so i just did it. but then after you reported issue
> 
> > i found the issue with time parsing, trakt and tmdb use different format. trakt also adds time, but unfortunately golang is not smart enough to just ignore it if we do not need it.

Ok,
Tell me when you have a new build to test.

**Comment by antonsoroko** [comment]
@burekas7 

>So what is the difference between "Synchronize frequency of Trakt" (According to the settings) and "Clear Trakt cache" which is 7 days that we mention here regarding the episodes count?

it **does not** matter for "episodes count". but you were talking about 

>There I was talking aboud Movies, when I add a movie in Trakt site but because it always show the list from cache, the movie isn't shown unless I clear it in order to force refresh the list.

not about "episodes count".

i thought that i already answered that question 2 years ago https://github.com/elgatito/plugin.video.elementum/issues/680#issuecomment-802866135

but let me add some extra details:
some things we update in background (e.g. something was added to "shows list"). thus we have "frequency" of how often we do that.
some things we get only when user asks for it (e.g. content of "shows list"). so then we keep data for 7 days or different time, see link to code above.

thus, if you asked to see content of list and list was not changed - then you see "old" data. but it is not actually old - since nothing actually changed - **list is the same**. i say nothing - because this feature "number of unwatched episodes" is unrelated to content of the list. so to make those numbers correct i had to "neglect numbers from Trakt and calculate them manually".

>I don't want to discuss on the issue of https://github.com/elgatito/plugin.video.elementum/issues/680 here, but the "Synchronize frequency of Trakt" action didn't affect on it unless I did Clear cache.

IT DOES. it does for me. it does for author.
let's be honest: some settings in your elementum are incorrectly. if you just have used default values - you would not have so many issues.
try to setup new elementum from scratch without modifying settings that you do not understand and you will see than many issues that you are having are not real. like you have not enabled "library_sync_enabled" so you had issue with sync to kodi library. you set "Synchronize frequency of Trakt" to **50 minutes** and then you were surprised that you do not see changes immediately.

**Comment by antonsoroko** [comment]
@burekas7 try this build https://disk.yandex.by/d/Z9veYtA9y1CU9g
 share log if you will have wrong numbers.

**Comment by burekas7** [comment]
> @burekas7 please try this build https://disk.yandex.by/d/Z9veYtA9y1CU9g share log if you will have wrong numbers.

Works well! 
Approved.
Thanks.

This is the log if you still need:
https://paste.ubuntu.com/p/n4ggmv8cfV/plain/

**Comment by elgatito** [comment]
@burekas7 Please, check with v0.1.99.

**Comment by burekas7** [comment]
> @burekas7 Please, check with v0.1.99.

Approved with v0.1.99.
Close here.
Thanks

@elgatito @antonsoroko
