### ISSUE TITLE
Opensubtitles.ORG api is shutting down at the end of the year

### ISSUE THREAD

**Issue by pitsi** [elgatito/plugin.video.elementum#952]
Preface: I do not use elementum's built in subtitle addon, neither the one provided by the main kodi repo. I use the opensubtitles_by_opensubtitles (the python3 compatible and still maintained fork by gujal) for the obvious reason.

So, I read on kodi_helpers' reddit today that the opensubtitles.ORG api is shutting down at the end of year and users must move to the .COM one (unless they are vip users who pay fees). On my end, the forementioned info showed up as part of a subtitle inside kodi a few days ago (screenshot upon request).
https://forum.opensubtitles.org/viewtopic.php?t=17930

I assume that this means that elementum's subtitle addon will stop working as well. I know the addon's development has stopped and this would be a somewhat big change in its code, but I wanted to mention it in case someone can do something.

**Comment by elgatito** [comment]
Have not seen this. Need to verify new api and see if we can switch to it.

**Comment by SubEdict** [comment]
@pitsi 
I'm already using .com. [Burekas repo](https://burekaskodi.github.io/repository.burekasKodi/) has manage to add to opensubtitle.com API section after the User/Password in his multi-subtitles addon.
You can install it without interfering or any conflict to any other subtitles addons as it uses different name "Opensubtitle-Plus".

Also it take 5 second to get API as a [new consumer](https://www.opensubtitles.com/en/consumers) ( Allow anonymous  + Under development will give you 100 downloads per day).

**Comment by antonsoroko** [comment]
@SubEdict JFYI: official Kodi repo has new [service.subtitles.opensubtitles-com](https://github.com/opensubtitlesdev/service.subtitles.opensubtitles-com) addon for a while. It uses its own api key, as i can see in code.

(although, those [service.subtitles.all_subs_plus](https://github.com/burekasKodi/repository.burekasKodi/tree/main/zips/service.subtitles.all_subs_plus) and [service.subtitles.opensubtitles_plus](https://github.com/burekasKodi/repository.burekasKodi/tree/main/zips/service.subtitles.opensubtitles_plus) addons might be interesting in general. )

**Comment by antonsoroko** [comment]
also from https://opensubtitles.stoplight.io/docs/opensubtitles-api/53fb2f26d5d50-wrappers-scripts-apps-using-opensubtitles-com-api
there is https://github.com/TheForgotten69/go-opensubtitles which looks ok at first sight.

**Comment by SubEdict** [comment]
Good to know @antonsoroko, 1 week and already so much info for 1 site lol. 
Wish they could just update the old one that already exist in the kodi repo. Why another new one with "-com".

Opensubtitle  history Headache:  .org/.org-free/.com/-com (free?)/go-opensubtitle (free?)/other devs: A4kSubtitle/All subtitle-Plus. 🤣

**Comment by pitsi** [comment]
@SubEdict 
Do all these addons demand credentials? If so, thanks but I'll pass.

**Comment by SubEdict** [comment]
@pitsi
As @antonsoroko just mentions [service.subtitles.opensubtitles-com](https://github.com/opensubtitlesdev/service.subtitles.opensubtitles-com) should be totally free and other 3 below except opensubtitles_plus.

** I tested 5 episodes (Best 48h trending w/subs):
1. -COM (from @antonsoroko git link and also from Kodi repo): **0 results** + Wrong results.
2. .ORG (Kodi repo): **0 results**
3. A4kSubtitles ([Repo](https://a4k-openproject.github.io/a4kSubtitles/packages/)): **3/5 results**. *90% good all year, but I'm not sure if they update anything.
4. Opensubtitles-Plus / Allsub-Plus ([Repo](https://burekaskodi.github.io/repository.burekasKodi/)): **5/5 results**. *99% success all year. ***Needs .com credentials +API**

**Comment by pitsi** [comment]
Tbh, I did not know about the plus one. 

Leaving com, org and plus aside because they demand credentials, we are left with a4ksubtitles only. 
It works great, but it has one major issue: it does not support manual search. If the video addon can not provide an imdbid for the stream/file it plays, a4ksubtitles is completely useless.

**Comment by SubEdict** [comment]
>a4ksubtitles...it does not support manual search. 

And that's exactly where All Sub Plus shines. Not only does it have a manual search if no ID/Meta is presented (For movies you type: Name + Year. For TV you type: Name + Season number + Episode number)

BTW, All Sub Plus is in the Services section of Burekas repo (because it can also let you auto-load sub), and it includes subcence & opensubtitles.com (Yes you need API) + Other subtitles site sub that probably not for you (Hebrew: Ktuvit/Wisdom).

*Also there's a contextual menu that lets you search subs without playing anything (That's Genius!).

**Comment by pitsi** [comment]
I am answering about the credentials part only, and I hope I won't get the same response I once (3.5 eyars ago) got at kodi's forums. Back then, credentials for accessing the api were only demanded for kodi's addon. For other apps like vlc, subliminal, mpc-hc, smplayer etc, credentials were completely optional and all of them were working without them. 
Tbh, I rarely use any of those other apps nowadays for downloading subtitles.

It is not about creating credentials with a fake email or something similar. It's about sh*t behaviors like this one, where they revealed that they got hacked ~6 months later.
https://forum.opensubtitles.org/viewtopic.php?t=17685

**Comment by antonsoroko** [comment]
so now org API is dead and thus elementum downloads their "dummy" subtitles with text like "upgrade to vip".

i think at some point (i mean then someone will have free time) we can switch to https://pkg.go.dev/github.com/TheForgotten69/go-opensubtitles@v1.0.0/opensubtitles

**Comment by davordragic** [comment]
It would be nice at least to update this repo with function to disable default elementum subtitiles and just depend on additional addons

**Comment by antonsoroko** [comment]
@davordragic what do you mean exactly? you can disable internal opensubtitles.org search in settings, option to do that always been there.

**Comment by pitsi** [comment]
As a user of elementum (and quasar before it), I have never seen the option to disable its internal subtitles search.
May I ask where is it? I don't know where every setting is located, but I do know most of them.

**Comment by davordragic** [comment]
No metter what are settings set, there is always Elementum first in download subs section
![IMG_2927](https://github.com/elgatito/plugin.video.elementum/assets/10212089/5ddc882c-edfa-4e0c-8210-e5cd69245c37)

**Comment by antonsoroko** [comment]
i meant that you can disable auto search so it will not download "dummy" subtitle file if there is no subtitles in video file. it will not disable elementum as subtitle provider.

**Comment by davordragic** [comment]
My suggestion was to make a option, to remove elementum as subtitle provider

**Comment by antonsoroko** [comment]
As a temporary solution you can use https://kodi.wiki/view/Add-on:AutoSubs - it can be configured to automatically download subtile from **chosen provider** if there is no subtitle in video file.

**Comment by davordragic** [comment]
AutoSubs does not work on my nvidia shield tv pro. When I install it, I just get a message that there is an error, check logs

**Comment by pitsi** [comment]
No offence but... check the logs then and see what makes it fail. There is the log viewer addon on the main repo, if you can not access the log otherwise (e.g. via ssh or from a file manager).

I do not use autosubs. I used a script with the same functionality once on mpv and I hated it, because I want to choose which subtitle gets downloaded.

**Comment by davordragic** [comment]
I did that. Found an open issue with Kodi 20+
https://github.com/amet/service.autosubs/issues/50

**Comment by antonsoroko** [comment]
@davordragic looks like they provided solution in that issue. also as i can see the fix was merged to repo, so you can click "Code"->"Download ZIP" on main page of that repo.

**Comment by antonsoroko** [comment]
anyway, back to the main issue: now opensubtitles alwasy demands user/password (unless user created its own api key with "dev mode" enabled - 90% of users will not do that, i think. also we do not know if they will disable this "dev mode" in future).
so i guess we would need to hide elementum as a subtitles provider if user have not supplied user/password - otherwise search will always fail.
or we can always show error that users/password is not provided, but this will be annoying for users.
we also can silently ignore search if there is no users/password - but this is also so-so UX.

**Comment by antonsoroko** [comment]
@elgatito so i tested this https://github.com/TheForgotten69/go-opensubtitles golang package.
It is old so i had to update it first - https://github.com/TheForgotten69/go-opensubtitles/pull/13
but now it works.
I also wrote an example of how to use it.

So i guess we can try to replace old package (which is copy of https://github.com/oz/osdb/tree/master as it turned out) with it.

**Comment by elgatito** [comment]
@antonsoroko To be honest, there are only few endpoints we use for OSDB, I would try using same approach we use for Fanart: https://github.com/elgatito/elementum/blob/master/fanart/fanart.go#L96

**Comment by elgatito** [comment]
I was not looking into this, whether we can register Elementum as an App (as we have with Fanart/TMDB/Trakt) and use this API key for everyone, without need to register personal keys.

**Comment by elgatito** [comment]
I created API key for Elementum, marked it as "under development" - HFMI55SCsDzByox4ZY8CVBLuxMSYvzCZ

I think it should allow using it for downloading subs, but would be limited to 5 downloads from IP per 24 hours, unless user is authorized.

**Comment by antonsoroko** [comment]
@elgatito 

>but would be limited to 5 downloads from IP per 24 hours,

i think dev_mode only affects downloads, not API calls.
with `dev_mode` "Downloads/24h"=100 as i understand this statement:

>Make sure everything works as expected before purchasing, you can fully test your API key up to 100 downloads per day with the "dev_mode" enabled

from https://www.opensubtitles.com/ru/consumers

but "API Request Limit/s IP" remains the same = 5. I guess they mean 5 per second (this "/s") per IP, which should be enough i think.

i guess they can remove this dev_mode "feature" at some point.
also i guess that 100 downloads might not be not enough.
but as i can see they have a statistics about usage of api key, so we can see it later.

but i would suggest to encourage users to use login, like add "help text" in settings near to "enable opensubtitles" option.

**Comment by elgatito** [comment]
@antonsoroko I pushed changes implementing Opensubtitles.com API. I also unchecked development mode. 

Would be great if you could test somehow it. I was trying with few movies, but I am not using things like that, so it is hard to see if that works properly.

**Comment by antonsoroko** [comment]
looks like it works!
i did only quick testing so far: i tested on movie and on episode.
but i also tested with different language settings in kodi and elementum - looks ok, at least at glance.

if someone want to test it - here is a new build: [plugin.video.elementum-v0.1.99-43-g5e99c5d.windows_x64.zip](https://disk.yandex.by/d/bj_rQ-toKNbulQ)
(if you need a build for different OS - ask for it)

**Comment by antonsoroko** [comment]
@elgatito 

about
>I also unchecked development mode.

i have re-read their statement
>Make sure everything works as expected before purchasing, you can fully test your API key up to 100 downloads per day with the "dev_mode" enabled

but i still do not get it, do they allow 100 anonymous downloads with "dev_mode" or not?

there is "Downloads Stats" (eye icon) for each api key on https://www.opensubtitles.com/en/consumers page. what does it says for your key?

also what
https://opensubtitles.stoplight.io/docs/opensubtitles-api/ea912bb244ef0-user-informations

says for you?

for me:
```
{
  "data": {
    "allowed_translations": 3,
    "allowed_downloads": 200,
    "level": "Gold Member",
    "user_id": 123,
    "ext_installed": false,
    "vip": false,
    "downloads_count": 0,
    "remaining_downloads": 200,
    "username": "123"
  }
}
```
so i have limit of 200, which i guess means that user has its own limitation that is not related to api key limitation.

**Comment by elgatito** [comment]
@antonsoroko 
My login response says:

```
 "user": {
        "allowed_translations": 1,
        "allowed_downloads": 20,
        "level": "Sub leecher",
        "user_id": ...,
        "ext_installed": false,
        "vip": false
    },
```

**Comment by elgatito** [comment]
@pitsi 

>  I do not use opensubtitles with credentials. 

Does it allow anonymous downloads? How you use it?

**Comment by antonsoroko** [comment]
@elgatito 
>But when I request download link for subtitles, I see that I only set ApiKey but do not set a token and I get this response:

I guess if you enable dev mode and do the same again you will see 99 (100-1) instead of 4 (5-1).

So maybe it makes sense to enable the dev mode and then enable anonymous download? 100 downloads per day might be enough for all Elementum users who do not have their own open subtitles accounts. What do you think?

**Comment by pitsi** [comment]
> @pitsi
> 
> > I do not use opensubtitles with credentials.
> 
> Does it allow anonymous downloads? How you use it?

Yes, it allow anonymous downloads, probably because of some very specific user agent it uses. Most of the times though, the first results, where it picks up the "original" name of the video, are wrong and the user has to do a manual search. I also do not know if there is a daily limit for the requests, because I download like 1 per day.

If you want, I can show you the "civilised discussion" I had with the devs of the original addon, when the api began breaking the addon deliberately so that more users would create credentials to their garbage page.

**Comment by antonsoroko** [comment]
@pitsi 
>it allow anonymous downloads

By "it" what do you mean exactly?

**Comment by pitsi** [comment]
It = opensubtitles **by opensubtitles**, an addon developed by the opensubtitles team back in the days of python2. That addon is long dead now, because it has not received a single update for 5 years. Imho, it was just used an excuse from the opensubtitles devs for people like me who do not want to create credentials for their garbage page/api.
https://github.com/opensubtitles/service.subtitles.opensubtitles_by_opensubtitles

Luckily. gujal has forked the addon and updates it regularly, and he has even ported it to python3

**Comment by antonsoroko** [comment]
@pitsi 
>Luckily. gujal has forked the addon, updates it regularly, and he has even ported it to python3.

do you have a link so we can read the code?

(i did a quick search and i have not found any new version of original addon that uses old api , only some unofficial addons that uses new api)

**Comment by pitsi** [comment]
I can not find the code for it, just the complete zip file here.
https://github.com/Gujal00/GujalKodiWork

**Comment by antonsoroko** [comment]
i have seen that one, but was confused by "Jun 5, 2022" last update date.
but if it still works - then cool.
maybe they still allow to use anonymous login with this "client name":
```
__scriptname__ = "XBMC Subtitles Unofficial"
login = self.server.LogIn(__addon__.getSetting("OSuser"), __addon__.getSetting("OSpass"), "en", 
"{0}_v{1}".format(__scriptname__.replace(" ", "_"), __version__))
```
e.g. "XBMC_Subtitles_Unofficial_v5.3.3"

**Comment by elgatito** [comment]
@pitsi @antonsoroko  

https://github.com/Gujal00/GujalKodiWork/blob/master/zips/service.subtitles.opensubtitles_by_opensubtitles/service.subtitles.opensubtitles_by_opensubtitles-5.3.3.zip

This addon is using `http://api.opensubtitles.org/xml-rpc` and not `https://api.opensubtitles.com`. 
I think we should not use `opensubtitles.org` anymore and `opensubtitles.com` has low limits for non-authorized downloads, and we discuss that thing now?

**Comment by antonsoroko** [comment]
@elgatito this is more like "general knowledge" conversation.
i mean, it looks like (from pitsi words)  that old api still works for that addon, maybe because  of that specific "user agent".
but i do not think we should try to use this hack. it can be deleted at any time.

i think the only final thing we can try is to enable "dev mode" and see if it will increase limit from 5 to 100. i mean this https://github.com/elgatito/plugin.video.elementum/issues/952#issuecomment-2069926326

**Comment by elgatito** [comment]
@antonsoroko I pushed a change to make login optional, so you can test it anonymously.

**Comment by antonsoroko** [comment]
@elgatito 
i just tested it with curl and VPN.

`curl -s https://api.opensubtitles.com/api/v1/subtitles?imdb_id=439572 --header 'Accept: application/json' --header 'Api-Key: HFMI55SCsDzByox4ZY8CVBLuxMSYvzCZ' --header 'Content-Type: application/json' --header 'User-Agent: Elementum v0.1.99'`
then 
`curl --request POST --url https://api.opensubtitles.com/api/v1/download --header 'Accept: application/json' --header 'Api-Key: HFMI55SCsDzByox4ZY8CVBLuxMSYvzCZ' --header 'Content-Type: application/json' --header 'User-Agent: Elementum v0.1.99' --data '{"file_id": XXXX}'`

you are right. it is 5 per IP.

and you are right about "dev mode" - it is 100 for ALL users, even with VPN i still see shared "remaining" number.

so i think it still makes sense to make login optional (without "dev mode"), but new error also need to be added, e.g. "anonymous download limit per day (5) is reached, please login into opensubtitles or wait for <value from "reset_time" field>".

**Comment by antonsoroko** [comment]
if limit is reached it gives `406` error code and 
```
{
  "requests": 5,
  "remaining": 0,
  "message": "You have downloaded your allowed 5 subtitles for 24h.Your quota will be renewed in 09 hours and 57 minutes (2024-04-23 23:59:59 UTC) ts=1713880932 ",
  "reset_time": "09 hours and 57 minutes",
  "reset_time_utc": "2024-04-23T23:59:59.000Z",
  "uk": "app_89836_87.252.225.91",
  "uid": 2,
  "ts": 1713880932
}
```

so i guess  "message" can be re-used for error.

**Comment by elgatito** [comment]
@antonsoroko I pushed a change to show a warning dialog when max downloads exceeded.

Anonymous work is also allowed.

**Comment by antonsoroko** [comment]
@elgatito 
I would suggest to change message to something more clear, to avoid confusion, e.g.:

"Exceeded anonymous daily allowed subtitles downloads. Enter credentials or wait untill next day."

**Comment by elgatito** [comment]
@antonsoroko I modified code to show response from them, because they say when limit will be reset. It is easier than guessing.

**Comment by antonsoroko** [comment]
@elgatito nice. that's exactly what i meant by 'so i guess "message" can be re-used for error.'

i think this issue can be closed.

**Comment by elgatito** [comment]
Closing the isssue. 
For any new issues with opensubtitles - should land as a new issue.
